name: CI/CD Pipeline with Security Scanning

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean compile

    - name: Run tests
      run: mvn test

    - name: Package application
      run: mvn package -DskipTests

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # SAST: Static Application Security Testing with SpotBugs
    - name: Run SpotBugs (SAST)
      run: |
        mvn compile
        mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.3.1:check

    # SCA: Software Composition Analysis with OWASP Dependency-Check
    - name: Run OWASP Dependency-Check (SCA)
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'secure-api'
        path: '.'
        format: 'ALL'
        args: >
          --enableRetired
          --enableExperimental
          --nvdValidForHours 24

    - name: Upload Dependency-Check results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-check-report
        path: reports/

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and package for deployment
      run: mvn clean package -DskipTests

    - name: Deploy to server (placeholder)
      run: |
        echo "Deployment step - replace with actual deployment logic"
        echo "Built JAR: target/secure-api-0.0.1-SNAPSHOT.jar"
