name: CI/CD Pipeline with Security Scanning

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean compile

    - name: Package application
      run: mvn package

  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # SAST: Static Application Security Testing with SpotBugs
    - name: Run SpotBugs (SAST)
      run: |
        mvn compile
        mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.3.1:check

    # SCA: Software Composition Analysis with Snyk
    - name: Run Snyk (SCA)
      uses: snyk/actions/cli@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=pom.xml --severity-threshold=high
      continue-on-error: true

    - name: Upload Snyk results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: snyk-report
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: [build, security-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and package for deployment
      run: mvn clean package

    - name: Deploy to server (placeholder)
      run: |
        echo "Deployment step - replace with actual deployment logic"
        echo "Built JAR: target/secure-api-0.0.1-SNAPSHOT.jar"
